<?php

namespace Tuf\ComposerIntegration\Tests;

use Composer\Json\JsonFile;
use Composer\Repository\FilesystemRepository;
use Tuf\ComposerIntegration\TufValidatedComposerRepository;

/**
 * Tests updating of root metadata when upstream TUF repo rotates its root keys.
 */
class RootMetadataRotationTest extends FunctionalTestBase
{
    /**
     * {@inheritDoc}
     */
    protected function setUp(): void
    {
        parent::setUp();
        $this->startServer();
        $this->composer(['require', 'php-tuf/composer-integration']);

        // Enable TUF protection at the command line so we know it works.
        $this->assertStringContainsString(
          "'fixture' is now protected by TUF.",
          $this->composer(['tuf:protect', 'fixture'])->getOutput(),
        );

        // Rotate the root key and re-publish metadata.
        $this->fixture->root->addKey();
        $this->fixture->root->revokeKey(0);
        $this->fixture->publish();
    }

    /**
     * Tests that updated root metadata is pulled in by our plugin.
     */
    public function testUpdatedRootMetadata(): void
    {
        // Run Composer in very, very verbose mode so that we can capture and assert the
        // debugging messages generated by the plugin, which will be logged to STDERR.
        $debug = $this->composer(['require', 'drupal/core-recommended', '--with-all-dependencies', '-vvv',])
          ->getErrorOutput();
        $this->assertStringContainsString('TUF integration enabled.', $debug);
        $this->assertStringContainsString('Downloading http://localhost:8080/metadata/2.root.json if modified', $debug);
        $this->assertStringNotContainsString('[404] http://localhost:8080/metadata/2.root.json', $debug);
        $this->assertStringContainsString('[304] http://localhost:8080/metadata/2.root.json', $debug);
    }

}
