<?php

namespace Tuf\ComposerIntegration\Tests;

/**
 * Tests updating of root metadata when upstream TUF repo rotates its root keys.
 */
class RootMetadataRotationTest extends FunctionalTestBase
{
    /**
     * The path to the new root metadata file.
     *
     * @var string
     */
    protected string $newRootMetadataPath;

    /**
     * {@inheritDoc}
     */
    protected function setUp(): void
    {
        parent::setUp();
        $this->startServer();
        $this->composer(['require', 'php-tuf/composer-integration']);

        // Enable TUF protection at the command line so we know it works.
        $this->assertStringContainsString(
            "'fixture' is now protected by TUF.",
            $this->composer(['tuf:protect', 'fixture'])->getOutput(),
        );

        $this->newRootMetadataPath = static::SERVER_ROOT . '/metadata/2.root.json';
        $this->assertFileDoesNotExist($this->newRootMetadataPath);

        // Rotate the root key and re-publish metadata.
        $this->fixture->root->addKey();
        $this->fixture->root->revokeKey(0);
        $this->fixture->publish();

        $this->assertFileExists($this->newRootMetadataPath);
        $rootJson = file_get_contents($this->newRootMetadataPath);
        $rootJson = json_decode($rootJson, true);
        $expectedVersion = 2;
        $actualVersion = $rootJson['signed']['version'];
        $this->assertEquals($expectedVersion, $actualVersion, "Expected root metadata version {$expectedVersion}, " .
          "got version {$actualVersion}.");
    }

    /**
     * Tests that updated root metadata is pulled in by our plugin.
     */
    public function testUpdatedRootMetadata(): void
    {
        // Check that the response from the server matches the file to be
        // served.
        $response = file_get_contents('http://localhost:8080/metadata/2.root.json');
        $this->assertJsonStringEqualsJsonFile($this->newRootMetadataPath, $response);

        // Run Composer in very, very verbose mode so that we can capture and assert the
        // debugging messages generated by the plugin, which will be logged to STDERR.
        $debug = $this->composer(['require', 'drupal/core-recommended', '--with-all-dependencies', '-vvv',])
          ->getErrorOutput();
        $this->assertStringContainsString('TUF integration enabled.', $debug);
        $this->assertStringContainsString('Downloading http://localhost:8080/metadata/2.root.json', $debug);
        $this->assertStringContainsString('[200] http://localhost:8080/metadata/2.root.json', $debug);
    }
}
