name: build-fixture
on:
  - push
jobs:
  fixture:
    name: Generate test fixture
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pip and pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
      - name: Install dependencies with pipenv
        run: |
          if [ -f Pipfile.lock ]; then pipenv --three install; fi
        working-directory: fixtures
      - name: Generate fixture
        run: pipenv run python generate.py
        working-directory: fixtures
