name: Drupal compatibility

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  composer-project:
    name: ${{ matrix.template }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        php: ['8.1', '8.2', '8.3']
        template:
          - recommended-project
          - legacy-project

    steps:
      - name: Checkout self
        uses: actions/checkout@v2
        with:
          path: composer-integration

      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Create Drupal project
        run: |
          composer create-project drupal/${{ matrix.template }} project
          cd project
          composer config --no-plugins allow-plugins.php-tuf/composer-integration true
          composer config repositories.local path ../composer-integration
          composer require php-tuf/composer-integration:@dev --with-all-dependencies
